### ISSUE TITLE
Attaching an extra storage area for Repository

### ISSUE THREAD

**Issue by LDSanches** [latam-tech-office/testdrive-openshift#1]
# This is my Ansible Version:
[lsanches@lsanches testdrive-openshift]$ ansible --version
ansible 2.6.2
  config file = /home/lsanches/GIT-REDHAT/testdrive-openshift/ansible.cfg
  configured module search path = [u'/home/lsanches/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

# This is the issue:
task path: /home/lsanches/GIT-REDHAT/testdrive-openshift/create-repository.yaml:70
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1533164789.45-250755225725178 `" && echo ansible-tmp-1533164789.45-250755225725178="` echo /root/.ansible/tmp/ansible-tmp-1533164789.45-250755225725178 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/google/gce_pd.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-28736EpVhmD/tmpzSfzkJ TO /root/.ansible/tmp/ansible-tmp-1533164789.45-250755225725178/gce_pd.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1533164789.45-250755225725178/ /root/.ansible/tmp/ansible-tmp-1533164789.45-250755225725178/gce_pd.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1533164789.45-250755225725178/gce_pd.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1533164789.45-250755225725178/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_zEggWp/ansible_module_gce_pd.py", line 196, in main
    disk = gce.ex_get_volume(name)
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 7109, in ex_get_volume
    return self._ex_lookup_volume(name, zone)
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 7405, in _ex_lookup_volume
    self._ex_populate_dict()

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "credentials_file": "/home/lsanches/Documents/Redhat/Sales/MBO/openshift-saches-fd3fe87ac311.json", 
            "delete_on_termination": null, 
            "detach_only": null, 
            "disk_type": "pd-standard", 
            "external_projects": null, 
            "image": null, 
            "image_family": null, 
            "instance_name": "openshift-repository", 
            "mode": "READ_WRITE", 
            "name": "openshift-repository-storage", 
            "pem_file": null, 
            "project_id": "openshift-saches", 
            "service_account_email": "lsanches@openshift-saches.iam.gserviceaccount.com", 
            "size_gb": "30", 
            "snapshot": null, 
            "state": "present", 
            "zone": "us-east1-c"
        }
    }, 
    "msg": "Unexpected response: ('GCENodeDriver' object has no attribute '_ex_populate_dict'). Detail: Traceback (most recent call last):\n  File \"/tmp/ansible_zEggWp/ansible_module_gce_pd.py\", line 196, in main\n    disk = gce.ex_get_volume(name)\n  File \"/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py\", line 7109, in ex_get_volume\n    return self._ex_lookup_volume(name, zone)\n  File \"/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py\", line 7405, in _ex_lookup_volume\n    self._ex_populate_dict()\nAttributeError: 'GCENodeDriver' object has no attribute '_ex_populate_dict'\n"
}
	to retry, use: --limit @/home/lsanches/GIT-REDHAT/testdrive-openshift/create-repository.retry

PLAY RECAP ***********************************************************************************************************************************************************************************
localhost                  : ok=13   changed=1    unreachable=0    failed=1   

# The workaround was manual disk adding on Google Cloud.

**Comment by LDSanches** [comment]
The same issue during the create_ops.yalm execution.

TASK [Attaching a Docker storage: leandro01-infra] *******************************************************************************************************************************************
task path: /home/lsanches/GIT-REDHAT/testdrive-openshift/create-ops.yaml:124
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: lsanches
<127.0.0.1> EXEC /bin/sh -c 'echo ~lsanches && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/lsanches/.ansible/tmp/ansible-tmp-1533913935.36-257060340208612 `" && echo ansible-tmp-1533913935.36-257060340208612="` echo /home/lsanches/.ansible/tmp/ansible-tmp-1533913935.36-257060340208612 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/google/gce_pd.py
<127.0.0.1> PUT /home/lsanches/.ansible/tmp/ansible-local-3081KV46X3/tmpsKC569 TO /home/lsanches/.ansible/tmp/ansible-tmp-1533913935.36-257060340208612/gce_pd.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/lsanches/.ansible/tmp/ansible-tmp-1533913935.36-257060340208612/ /home/lsanches/.ansible/tmp/ansible-tmp-1533913935.36-257060340208612/gce_pd.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/lsanches/.ansible/tmp/ansible-tmp-1533913935.36-257060340208612/gce_pd.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/lsanches/.ansible/tmp/ansible-tmp-1533913935.36-257060340208612/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_xxa5Ja/ansible_module_gce_pd.py", line 196, in main
    disk = gce.ex_get_volume(name)
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 7109, in ex_get_volume
    return self._ex_lookup_volume(name, zone)
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 7405, in _ex_lookup_volume
    self._ex_populate_dict()

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "credentials_file": "/home/lsanches/Documents/Redhat/Sales/SA/MBO/openshift-saches-fd3fe87ac311.json", 
            "delete_on_termination": true, 
            "detach_only": null, 
            "disk_type": "pd-standard", 
            "external_projects": null, 
            "image": null, 
            "image_family": null, 
            "instance_name": "leandro01-infra", 
            "mode": "READ_WRITE", 
            "name": "leandro01-infra-docker", 
            "pem_file": null, 
            "project_id": "openshift-saches", 
            "service_account_email": "lsanches@openshift-saches.iam.gserviceaccount.com", 
            "size_gb": "20", 
            "snapshot": null, 
            "state": "present", 
            "zone": "us-east1-c"
        }
    }, 
    "msg": "Unexpected response: ('GCENodeDriver' object has no attribute '_ex_populate_dict'). Detail: Traceback (most recent call last):\n  File \"/tmp/ansible_xxa5Ja/ansible_module_gce_pd.py\", line 196, in main\n    disk = gce.ex_get_volume(name)\n  File \"/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py\", line 7109, in ex_get_volume\n    return self._ex_lookup_volume(name, zone)\n  File \"/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py\", line 7405, in _ex_lookup_volume\n    self._ex_populate_dict()\nAttributeError: 'GCENodeDriver' object has no attribute '_ex_populate_dict'\n"
}
	to retry, use: --limit @/home/lsanches/GIT-REDHAT/testdrive-openshift/create-ops.retry

PLAY RECAP ***********************************************************************************************************************************************************************************
localhost                  : ok=22   changed=1    unreachable=0    failed=1

**Comment by LDSanches** [comment]
# I updated the apache-libcloud to 2.3.0.

apache-libcloud (2.3.0)                - A standard Python library that abstracts away differences among multiple cloud provider APIs. For more information and documentation, please see
                                         http://libcloud.apache.org
  INSTALLED: 2.0.0rc2
  LATEST:    2.3.0

# Now is working fine.

TASK [Attaching a Docker storage: leandro01-master] ******************************************************************************************************************************************
task path: /home/lsanches/GIT-REDHAT/testdrive-openshift/create-ops.yaml:84
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "echo /root/.ansible/tmp/ansible-tmp-1533926578.67-117044666478565" && echo ansible-tmp-1533926578.67-117044666478565="echo /root/.ansible/tmp/ansible-tmp-1533926578.67-117044666478565" ) && sleep 0'
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/basic.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/gce.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/_text.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/parsing/init.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/pycompat24.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/six/init.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/gcp.py
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/google/gce_pd.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-24775eOUdcH/tmps2qwnJ TO /root/.ansible/tmp/ansible-tmp-1533926578.67-117044666478565/gce_pd.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1533926578.67-117044666478565/ /root/.ansible/tmp/ansible-tmp-1533926578.67-117044666478565/gce_pd.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1533926578.67-117044666478565/gce_pd.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1533926578.67-117044666478565/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
"attached_mode": "READ_WRITE",
"attached_to_instance": "leandro01-master",
"changed": true,
"delete_on_termination": true,
"disk_type": "pd-standard",
"invocation": {
"module_args": {
"credentials_file": "",
"delete_on_termination": true,
"detach_only": null,
"disk_type": "pd-standard",
"external_projects": null,
"image": null,
"image_family": null,
"instance_name": "leandro01-master",
"mode": "READ_WRITE",
"name": "leandro01-master-docker",
"pem_file": null,
"project_id": "openshift-saches",
"service_account_email": "",
"size_gb": "20",
"snapshot": null,
"state": "present",
"zone": "us-east1-c"
}
},
"name": "leandro01-master-docker",
"size_gb": 20,
"state": "present",
"zone": "us-east1-c"
}
Read vars_file 'gce/authentication'
Read vars_file 'gce/defaults'
Read vars_file 'notification/mail_authentication'
